#!/bin/bash
# Script to integrate advanced visualization functions into Q_viz_intensity.py

echo "=== Advanced Visualization Integration Script ==="
echo ""
echo "This script will:"
echo "1. Backup the current Q_viz_intensity.py"
echo "2. Add the 5 new advanced visualization functions"
echo "3. Update the main controller and argument parser"
echo ""
echo "Files created for reference:"
echo "  - Q_viz_intensity_advanced.py (functions 1-3)"
echo "  - Q_viz_intensity_advanced_part2.py (functions 4-5)"
echo "  - advanced_functions_to_insert.py (all functions consolidated)"
echo "  - ADVANCED_VIZ_INTEGRATION_GUIDE.md (integration guide)"
echo ""
echo "MANUAL INTEGRATION REQUIRED:"
echo ""
echo "Step 1: Copy all functions from 'advanced_functions_to_insert.py'"
echo "        and paste them into Q_viz_intensity.py after line 341"
echo "        (after generate_std_dev_report() function)"
echo ""
echo "Step 2: Update visualize_tic_intensity() function signature (line 345):"
echo "        FROM: def visualize_tic_intensity(csv_file_path: str, output_base_dir: Optional[str] = None):"
echo "        TO:   def visualize_tic_intensity(csv_file_path: str, output_base_dir: Optional[str] = None, enable_advanced: bool = False):"
echo ""
echo "Step 3: Add after line 413 (after generate_std_dev_report(viz_data, output_dir)):"
echo "        # Generate advanced visualizations if requested"
echo "        if enable_advanced:"
echo "            create_advanced_visualizations(viz_data, df, str(output_dir), project_name)"
echo ""
echo "Step 4: Add to parse_arguments() after line 437:"
echo "        parser.add_argument("
echo "            '--advanced',"
echo "            action='store_true',"
echo "            help='Enable advanced visualizations (heatmap, grouped barplot, dotplot, statistical swarmplot, forest plot).'"
echo "        )"
echo ""
echo "Step 5: Update main() function (line 444):"
echo "        FROM: visualize_tic_intensity(args.input, args.output)"
echo "        TO:   visualize_tic_intensity(args.input, args.output, args.advanced)"
echo ""
echo "=== Test Command ==="
echo "python Q_viz_intensity.py --input data/qc/results/solventmatrix/organized/organized_QC_solventmatrix_RESULTS.csv --advanced"
echo ""
echo "See ADVANCED_VIZ_INTEGRATION_GUIDE.md for detailed instructions."
